### ISSUE TITLE
MPQ file manipulation tests do not check if files were manipulated.

### ISSUE THREAD

**Issue by DrSuperGood** [inwc3/JMPQ3#16]
The tests do not check if any files were manipulated. When there was an error in the file key generation algorithm the result was that all tests passed because there were no files in any of the MPQs. Reading files from the test MPQs should verify they exist after extraction and also that the extracted content matches a sha-1 hash of the expected content.

**Comment by Frotty** [comment]
True. Especially also files being the same after write->extract was crucial for finding some other bugs.
I assign this to me if you don't mind.
