### ISSUE TITLE
Make keepHeaderOffset configurable and correct

### ISSUE THREAD

**Issue by Frotty** [inwc3/JMPQ3#18]
@DrSuperGood 
https://github.com/inwc3/JMPQ3/blob/master/src/main/java/systems/crigges/jmpq3/JMpqEditor.java#L95

It's always true and cannot be changed by the user. Just changing it doesn't work properly though, because the headerOffset value isn't changed when the offset shall not be kept.

https://github.com/inwc3/JMPQ3/blob/master/src/main/java/systems/crigges/jmpq3/JMpqEditor.java#L701

Nothing important, but for rebuilding protected mpqs this will be required I think.

**Comment by DrSuperGood** [comment]
Header offset value can/should only really be specified when first creating an archive. When loading an existing archive the value is automatically detected and has to be used for rebuilding so as not to discard the data that exists before the MPQ archive starts.

The header offset specifies the offset of the MPQ archive data inside a file. The archive size specifies the size of the MPQ archive data inside a file. Other data can exist both before and after the MPQ archive data in a file. During rebuild this data must not be modified.

Possibly a method could be added to modify the offset of the MPQ archive data when rebuilding the archive. One would have to 0 pad or truncate data before the archive data as appropriate.

**Comment by Frotty** [comment]
one can now choose whether to keep the pre-mpq data or not.
