### ISSUE TITLE
NegativeArraySizeException

### ISSUE THREAD

**Issue by peq** [inwc3/JMPQ3#19]
We get the following exception when trying to extract the w3u data from a map in Wurst:

```
java.lang.NegativeArraySizeException
	at systems.crigges.jmpq3.MpqFile.getSectorAsByteArray(MpqFile.java:334)
	at systems.crigges.jmpq3.MpqFile.extractToOutputStream(MpqFile.java:116)
	at systems.crigges.jmpq3.MpqFile.extractToBytes(MpqFile.java:75)
	at systems.crigges.jmpq3.JMpqEditor.extractFileAsBytes(JMpqEditor.java:519)
```

> (19:34:05) Frotty: bekomem so was bei ner recht großen asia map
> (19:34:25) Frotty: kommt immer negativearraysize wenn ich bei runmap die auswähle
> (19:34:27) Frotty: andere maps gehen
> (19:34:41) Frotty: hast ne idee?
> (19:36:35) Frotty: https://mega.nz/#!CZw0xIrR!CevOolg-bcSPuAONFM56brs4Ovd9QSl2yuOMUXmN15c
> (19:36:37) Frotty: das ist die map

@Frotty do you want to look at it? At the moment I don't have the nerves to debug the mpq library ;)

JMPQ-Version: `com.github.inwc3:JMPQ3:1.5.3`

**Comment by Frotty** [comment]
Slightly OT for wurst: My first suggestion would be to output this error properly to the user instead of showing it at the first object generation in the user's code.

negative arraysize usually indicates something is missing. iirc another user didn't get this error when he had the sound/model mpq mods. So need to investigate further here.

**Comment by DrSuperGood** [comment]
Was the map protected? It is possible some protectors might have purposely inserted nonsense or corrupted block table entries that WC3 MPQ implementation can parse but this cannot.

**Comment by Frotty** [comment]
Nope, I don't think it's protected. The only special thing about this map and the reason you cannot open in world editor/wc3 is that it requires mod-mpqs/mix files for all the models/sounds.
However this really shouldn't matter, mpq editor can open it fine, and not in read-only mode.

**Comment by DrSuperGood** [comment]
The library reads the file fine. Something is wrong with rebuilding the archive as the error is only thrown after the MPQ has been rebuilt by JMPQ3. In fact the MPQ is likely entirely corrupt as not even MPQEdit can open it.

**Comment by Frotty** [comment]
The mpq can be opened fine with mpq editor -.- @DrSuperGood
https://i.imgur.com/1Jq9M3V.png (open in mpqeditor)
https://i.imgur.com/KkHO16z.png (external file added and mpq rebuilt)

The reason why jmpq can't build it is way more simple: The mpq contains blocks which don't have an entry in the listfile, which jmpq can't handle yet or entries in listfile which don't have accompanied blocks.

**Comment by DrSuperGood** [comment]
Code that can recreate this error may be required. My test code only cannot read the w3u file after JMPQ has opened the archive once in non read only mode. The link provided above in the chat log is what I was using as the source file and tested it multiple times, using both extract to file and extract as bytes.

**Comment by Frotty** [comment]
Should be fixed.
