### ISSUE TITLE
just warning for `insertByteArray` when listFile contains filename

### ISSUE THREAD

**Issue by PhoenixZeng** [inwc3/JMPQ3#33]
JMpqEditor.java line 650 and 675

**Comment by PhoenixZeng** [comment]
replace file is a normal demand. 
and i think delete file before insert is stupid
i used to use the 1.7.7 version. it is ok for this question

**Comment by Frotty** [comment]
you could make a PR for a replace function.
I'd like to keep insert safe.

**Comment by PhoenixZeng** [comment]
how about add a bool parameter called 'override'

**Comment by PhoenixZeng** [comment]
#34
