### ISSUE TITLE
how to open jmpq3.jar

### ISSUE THREAD

**Issue by fds433aaz** [inwc3/JMPQ3#35]
file is not running my pc is windows7
i used by cmd 
file is not open
![11111111](https://user-images.githubusercontent.com/64178051/80050354-46761900-84a0-11ea-87bc-0996f64c8bd9.PNG)

i want really use this software

**Comment by Frotty** [comment]
This is a library meant to be used in Java code, it has no CLI function.
If you want an editor, use http://www.zezula.net/en/mpq/download.html
