### ISSUE TITLE
Allow saving of MPQs without rebuilding

### ISSUE THREAD

**Issue by zach-cloud** [inwc3/JMPQ3#37]
As a user, I would like to be able to save an MPQ Archive without having to rebuild the entire archive so that I can avoid data loss from incomplete listfiles and to improve the performance of saving the archive.

(to be clear: I intend to code this)

**Comment by zach-cloud** [comment]
I decided to code my own implementation here: https://github.com/zach-cloud/Frost

If you're interested in how I coded importing:
https://github.com/zach-cloud/Frost/blob/6c276e1d86dfd39877811eeebeb8c84e733a61b1/src/main/java/model/MpqObject.java#L382
Basically find an available hashtable spot, allocate a new block table and file data, and then re-organize everything in the MPQ as such:
https://github.com/zach-cloud/Frost/blob/6c276e1d86dfd39877811eeebeb8c84e733a61b1/src/main/java/model/MpqObject.java#L449
I put things in order of header - file data - hash table - block table.
You need to leave encrypted files in the same spot they were originally at due to key shift
The rest of them get new space allocated.

This allows saving and importing of any type of mpq (even corrupted ones)

**Comment by Frotty** [comment]
cool
