### ISSUE TITLE
can i use Multithreading read w3x or write?

### ISSUE THREAD

**Issue by qq1053831109** [inwc3/JMPQ3#39]
can i use Multithreading read w3x or write?

**Comment by Crigges** [comment]
For multithreaded read I added the method https://github.com/inwc3/JMPQ3/blob/849f0fb49651c4845d09dc628ac43b5a80e76da3/src/main/java/systems/crigges/jmpq3/JMpqEditor.java#L608
The method itself is not threadsafe but you can create a new thread for each `MpqFile` file for extraction. Multithreaded write is unsupported unless @Frotty did implement something there.

**Comment by qq1053831109** [comment]
mpqFile.extractToOutputStream(byteArrayOutputStream); 
is not threadsafe

**Comment by qq1053831109** [comment]
now i only can do this:
            MpqFile mpqFile = jMpqEditor.getMpqFile(fileName);
            ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
            mpqFile.extractToOutputStream(byteArrayOutputStream);
            ThreadUtil.execute(() -> {
                File toFile = new File(toDir + fileName);
                if (toFile.exists()) {
                    return;
                }
                FileUtil.mkParentDirs(toFile);
                try {
                    byte[] fileBytes = byteArrayOutputStream.toByteArray();
                    byteArrayOutputStream.close();
                    FileUtil.writeToFile(fileBytes, toFile);
                } catch (Exception e) {
                    e.printStackTrace();
                }
                FileUtil.cacheLastModified(toFile);
            });

**Comment by Crigges** [comment]
> ```
>         mpqFile.extractToOutputStream(byteArrayOutputStream); 
> ```
> is not threadsafe

If that is true then you are out of luck. I guess I didn't check that all underlying calls are of `MpqFile.extractToOutputStream(Outputstream)` are threadsafe.

So you have only two options left. You implement the thread-safety yourself and create a pull request. Or you make copies of the archive and create multiple instances of the MpqEditor.

**Comment by Frotty** [comment]
What is your goal here anyway? What benefit do you expect from multithreading in your use case?
Jmpq isn't optimized for performance, but runs reasonably fast for regular archives.
Unless you have some way oversized mpq or want to process thousands of maps quickly, I don't see the point in multi threading.
I would assume that you could gain more speed with other code improvements.
Also the multi threading will probably be blocked by disk access anyway. 🤷

**Comment by qq1053831109** [comment]
i really need Multithreading read w3x!
i have a w3x editor(www.heduim.com)
it can Improve open file speed!

**Comment by Frotty** [comment]
Please read my last message - you haven't answered anything from it. Please consider doing so.
How big is your map? Why do you think multi threading would give you a performance benefit?

**Comment by qq1053831109** [comment]
in china ,we map Map size is generally in 100 - 256mb.  Many  mdx models in map. now the read Time is 10 - 30 second. my ssd Disk read speed is 200M per second。 so i think it,s jmpq algorithm Slow down the speed。 i want the read map speed come close Disk read speed.Sorry about my English. maybe can read one map all files in 2 second to  Memory.

**Comment by Frotty** [comment]
> in china ,we map Map size is generally in 100 - 256mb. Many mdx models in map. now the read Time is 10 - 30 second

I think ~20 seconds sounds fine for 200MB of compressed data.

> my ssd Disk read speed is 200M per second。 so i think it,s jmpq algorithm Slow down the speed

I just profiled it for fun - roughly 80%+ of the required time is simply (de)compression/io.
![image](https://user-images.githubusercontent.com/1486037/129969062-f873aa60-d9de-4984-a9ab-7638069c2b71.png)

So no, it's not the 'jmpq algorithm'.

> i want the read map speed come close Disk read speed.Sorry about my English. maybe can read one map all files in 2 second to Memory.

I think that's a fallacy because you will not easily get access to encrypted and compressed data at disk read speeds.
Also jmpq simply wasn't made with the intention of high throughput.
I would suggest that you implement in your editor application two things:
- Load mpq files asynchronously in the background, so you don't have to wait the entire extraction time
- Cache the extracted files, and then use the cached files on next load for instant access

edit: Also, I already pushed fixed for better write speed when recompress isn't enabled, but version not released yet.

**Comment by qq1053831109** [comment]
jzlib is not threadsafe

java.lang.NullPointerException: Cannot store to int array because "this.blens" is null
	at com.jcraft.jzlib.InfBlocks.proc(InfBlocks.java:313)

**Comment by qq1053831109** [comment]
why use static ? in one jvm only one thread can use jmpq3

public class JzLibHelper {
    private static final Inflater inf = new Inflater();

    private static int defLvl = 0;
    private static Deflater def = null;

    public static byte[] inflate(byte[] bytes, int offset, int uncompSize) {
