### ISSUE TITLE
export MpqFile from ENCRYPTED Block

### ISSUE THREAD

**Issue by PhoenixZeng** [inwc3/JMPQ3#40]
i made this code ago.  but i have a mpq file with all encrypted block.

https://github.com/inwc3/JMPQ3/blob/849f0fb49651c4845d09dc628ac43b5a80e76da3/src/main/java/systems/crigges/jmpq3/JMpqEditor.java#L627

i skip the `if` .  and the `start` is negative. on this line
https://github.com/inwc3/JMPQ3/blob/849f0fb49651c4845d09dc628ac43b5a80e76da3/src/main/java/systems/crigges/jmpq3/MpqFile.java#L105

the mpq file is a big one. size 1.6GB

**Comment by Frotty** [comment]
dunno what this has to do with the encrypted flag - would need the mpq to reproduce the issue.
Perhaps related to size, jmpq was pretty much only intended for wc3 maps.

**Comment by PhoenixZeng** [comment]
it's too big to upload. and it's a wc3 map model pack
i will keep close this issue  before I find a way to reduce its size,

**Comment by Frotty** [comment]
isn't there a downloadlink somewhere?
Also, maybe you can make a smaller example.
