### ISSUE TITLE
Tempfile swamp

### ISSUE THREAD

**Issue by WaterKnight** [inwc3/JMPQ3#7]
JMPQ creates tons of temp files and does not clean up them partially respectively temp files are difficult to begin with when the thread/application crashes/ends abruptly. Can it not rather use a fixed folder and refresh it on initialization or bestow the folder choice upon the user as he/she may want to use multiple instances of JMPQ in parallel.

**Comment by Crigges** [comment]
Well thoose tempfiles should be deleted after the jvm exits, ill check the delete on exit flags for all tempfiles. Even if the thread/application crashes/ends those files should be deleted and even if not, a restart will remove them all.
However normaly JMPQ wouldn't create that much temp files. Thoose are just workaround for the MappedByteBuffer bug see: http://bugs.java.com/view_bug.do?bug_id=4724038

I may add an option for an custom temp file creator. Which will allow you to pass some "TempFileFactory" to the editor.

**Comment by Frotty** [comment]
Delete on exit flags were missing in 4 out of 5 cases. They should all be deleted now, but it's still not the best solution.
