### ISSUE TITLE
Listfile null exception

### ISSUE THREAD

**Issue by WaterKnight** [inwc3/JMPQ3#8]
When closing an mpq, JMpqEditor.calcNewTableSize may throw NullException on listFile since apparently it can be null at this point. The constructor tries to check if there is a listfile and extracts it but may fail in doing so, which is caught and listFile is set/remains null. Also the whole writing part in the JMPQ.close method will be unnecessarily done if you do not add files to the mpq.

**Comment by Crigges** [comment]
I will add a handling in case of listFile is null.

Rebuilding is part of the close function since files get recompressed which may often result in better filesizes.
However i may add an flag to check if the mpq was edited to prevent unnecressary rebuilding.
